In [1]:
import tensorflow as tf
from tensorflow import keras

In [33]:
inputs = keras.Input((16,))
x = keras.layers.Dense(5)(inputs)
y = keras.layers.Dense(5)(inputs)

stacked = keras.ops.concatenate([keras.ops.expand_dims(x, axis=1),keras.ops.expand_dims(y, axis=1)], axis=1)
print(stacked)

x = tf.constant([[1,2,3,4,5]])
y = tf.constant([[6,7,8,9,10]])
tf.stack([x,y], axis=1)

<KerasTensor shape=(None, 2, 5), dtype=float32, sparse=False, name=keras_tensor_83>


<tf.Tensor: shape=(1, 2, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]], dtype=int32)>

In [38]:
def stack_keras_tensors(tensors, axis=0):
    """Stacks a list of rank-`R` tensors into one rank-`(R+1)` tensor."""
    return keras.ops.concatenate([keras.ops.expand_dims(t, axis=axis) for t in tensors], axis=axis)

inputs = keras.Input((16,))
x = keras.layers.Dense(5)(inputs)
y = keras.layers.Dense(5)(inputs)
stack_keras_tensors([x,y], axis=1)

<KerasTensor shape=(None, 2, 5), dtype=float32, sparse=False, name=keras_tensor_100>

In [47]:
inputs = keras.Input((16,))
x = keras.layers.Dense(5)(inputs)
x.shape[-1]

5

In [143]:
embedding = tf.constant([[[1,2,3,4,5]]])
_, num_static, static_dim = embedding.shape[-3:]
shape = tf.shape(embedding)
foo = tf.concat([shape[:-2], [num_static * static_dim]], axis=-1)
flatten = tf.reshape(
    embedding, tf.concat([shape[:-2], [num_static * static_dim]], axis=-1)
)
print(embedding)
print(foo)
print(flatten)

tf.Tensor([[[1 2 3 4 5]]], shape=(1, 1, 5), dtype=int32)
tf.Tensor([1 5], shape=(2,), dtype=int32)
tf.Tensor([[1 2 3 4 5]], shape=(1, 5), dtype=int32)


In [148]:
embedding = keras.Input((1,5))
_, num_static, static_dim = embedding.shape[-3:]
shape = embedding.shape
new_shape = list(shape[:-2]) + [num_static * static_dim]
flatten = keras.ops.reshape(embedding, new_shape)
print(embedding)
print(foo)

<KerasTensor shape=(None, 1, 5), dtype=float32, sparse=False, name=keras_tensor_168>
[None, 5]


In [201]:
import numpy as np
from keras import Layer, Model
class GetShapeLayer(Layer):
    def call(self, x):
        return tf.shape(x)

self_attn_inputs = keras.Input((252, 5))
shape = GetShapeLayer()(self_attn_inputs)
len_s = shape[-2]
bs = shape[0]
mask = tf.eye(len_s)
model = Model(self_attn_inputs, mask)
model(tf.constant(np.ones((2,252,5)))).numpy()

AttributeError: 'KerasTensor' object has no attribute 'numpy'

In [197]:
help(keras.ops.eye)

Help on function eye in module keras.src.ops.numpy:

eye(N, M=None, k=0, dtype=None)
    Return a 2-D tensor with ones on the diagonal and zeros elsewhere.
    
    Args:
        N: Number of rows in the output.
        M: Number of columns in the output. If `None`, defaults to `N`.
        k: Index of the diagonal: 0 (the default) refers to the main
            diagonal, a positive value refers to an upper diagonal,
            and a negative value to a lower diagonal.
        dtype: Data type of the returned tensor.
    
    Returns:
        Tensor with ones on the k-th diagonal and zeros elsewhere.

